services:
  app.api.internal_v1.server:
    class: UMA\JsonRpc\Server
    factory: [ '@App\Api\ServerFactory', 'create' ]
    arguments:
      $container: '@service_container'
      $methods:
        getHistory: app.api.internal_v1.method.get_history

  app.api.internal_v1.method.get_history:
    class: App\Api\Internal\V1\GetHistory
    public: true